# Generated by Django 4.2.1 on 2023-06-27 13:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0002_rename_profile_accountsettings"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AccountSettings",
            new_name="Profile",
        ),
    ]
