# Generated by Django 4.2.1 on 2023-05-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_language"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookinstance",
            options={"ordering": ["date_posted"]},
        ),
        migrations.RenameField(
            model_name="bookinstance",
            old_name="due_back",
            new_name="date_posted",
        ),
        migrations.AlterField(
            model_name="bookinstance",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("a", "Available"), ("s", "Swapped")],
                default="m",
                help_text="Book availability",
                max_length=1,
            ),
        ),
    ]
