# Generated by Django 4.2.1 on 2023-05-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_bookinstance_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinstance",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("l", "Like New"),
                    ("v", "Very Good"),
                    ("g", "Good"),
                    ("a", "Acceptable"),
                ],
                default="m",
                help_text="Book Condition",
                max_length=1,
            ),
        ),
    ]
