# Generated by Django 4.2.1 on 2023-05-31 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_bookinstance_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinstance",
            name="date_posted",
            field=models.DateField(default=datetime.date.today, verbose_name="Date"),
        ),
    ]
