# Generated by Django 4.2.1 on 2023-05-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_bookinstance_date_posted"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("h", "Hardcover"), ("p", "Paperback")],
                default="m",
                help_text="Book type",
                max_length=1,
            ),
        ),
    ]
