# Generated by Django 4.2.1 on 2023-06-06 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_genre_options_bookinstance_swap_with"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookinstance",
            options={
                "ordering": ["date_posted"],
                "permissions": (("can_mark_swapped", "Set book as shipped"),),
            },
        ),
        migrations.RenameField(
            model_name="bookinstance",
            old_name="swap_with",
            new_name="swapped_with",
        ),
    ]
