# Generated by Django 4.2.1 on 2023-06-22 14:37

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_remove_author_date_of_death"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={
                "ordering": [
                    "last_name",
                    django.db.models.functions.text.Lower("first_name"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": [django.db.models.functions.text.Lower("title")]},
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"ordering": [django.db.models.functions.text.Lower("name")]},
        ),
    ]
