# Generated by Django 4.2.1 on 2023-06-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_alter_author_options_alter_book_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="isbn",
        ),
    ]
