name: ci
on:
  pull_request:
    branches: [ main ]
  # push:
  #   branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: copy files to server
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
        chmod 600 ~/.ssh/id_rsa
        ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.SSH_SERVER }} "mkdir -p /app"
        scp -i ~/.ssh/id_rsa ./README.md ubuntu@${{ secrets.SSH_SERVER }}:/app
